### PR TITLE
Add directory scanning and getter methods and namespace prefixing to service provider

### LINKED ISSUE #3: [FEATURE] Root Namespace
The `RouteServiceProvider` in laravel 5 (at this point in time...!) has a `$namespace` property, that is prepended to all controllers - so you can just write
```php
    protected $scanRoutes = ['Auth\Login'];
```
instead of
```php
    protected $scanRoutes = ['AppName\Http\Controllers\Auth\Login'];
```
It would be nice to have a similar thing in the `AnnotationServiceProvider` to help keep the service provider file clean. It could default to `''` for backwards compatibility.

Happy to PR this.

### PR DESCRIPTION
**Pull request by tedslittlerobot**
This has #6 merged into it (resolves #3) (to avoid conflicts later on).

I have added usage notes to the readme, and hopefully commented everything so that it is relatively straightforward to understand what i've added.

The only thing in #4 i have not added yet is the fourth thing i suggested - i wanted to get opinions on this so far before doing that. I can do that in a separate PR, as well.

I've tested all the new methods - hopefully that's enough for now :)

### CODE REVIEW

**Comment by kirkbushell** [comment]
If I may offer a suggestion? I dont think namespace prefixing is really necessary, especially with PHP 5.6 which allows you to use the ::class notation on class names (allowing you to import them at the top of the page).

This is also rather confusing with ROUTE prefixes, which is about doing things like:

```
Route::get('users', ['prefix' => 'admin', 'uses' => 'UserController@show']);
```

Route prefixes is what we need in our own package, but not for prefixing namespaces. If you want to prefix namespaces, please make the naming of it a little clearer. 

I highly recommend however that it simply not be supported (I don't think it's necessary).

**Comment by kirkbushell** [comment]
Thanks for your input @tedslittlerobot :)

**Comment by varghesejacob** [comment]
the  ::class prefix can be used with 5.5 also, not just 5.6

**Comment by adamgoose** [comment]
Could you please re-submit this to LaravelCollective/annotations?

**Pull request closed without merging**
